# Generated by Django 4.0.2 on 2022-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
        ('member', '0003_rename_user_profile_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='rosters',
            field=models.ManyToManyField(blank=True, related_name='members', to='roster.Roster'),
        ),
    ]
