# Generated by Django 4.0.2 on 2022-07-29 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_initial'),
        ('roster', '0002_alter_cluster_locations_alter_cluster_managers'),
        ('member', '0005_remove_profile_photo_member_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allowed_to_meet',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='authorized_kiosks',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='kiosk.Kiosk'),
        ),
        migrations.AddField(
            model_name='member',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='roster.shift'),
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
