# Generated by Django 4.0.2 on 2022-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_allowed_to_meet_member_authorized_kiosks_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='member',
            name='employee_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='org_and_user'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_id'), name='org_and_employee_id'),
        ),
    ]
