# Generated by Django 4.0.2 on 2022-07-29 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_alter_cluster_locations_alter_cluster_managers'),
        ('member', '0007_alter_member_unique_together_member_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='roster.shift'),
        ),
    ]
