# Generated by Django 4.0.2 on 2022-07-29 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_member_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='photo',
        ),
    ]
