# Generated by Django 4.0.2 on 2022-07-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_initial'),
        ('member', '0011_remove_profile_photo_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='authorized_kiosks',
            field=models.ManyToManyField(blank=True, related_name='members', to='kiosk.Kiosk'),
        ),
    ]
