# Generated by Django 4.0.2 on 2022-08-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_member_authorized_kiosks'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
