# Generated by Django 4.0.2 on 2022-08-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_profile_marital_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
