# Generated by Django 4.0.2 on 2022-08-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_remove_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='shift',
        ),
    ]
