# Generated by Django 4.0.2 on 2022-09-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_member_applicable_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='organization_location',
            new_name='org_location',
        ),
    ]
