# Generated by Django 4.0.2 on 2022-09-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_rename_organization_location_member_org_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='org_location',
            new_name='organization_location',
        ),
    ]
