# Generated by Django 4.0.2 on 2022-09-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_rename_org_location_member_organization_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='organization_location',
            new_name='org_location',
        ),
    ]
