# Generated by Django 4.0.2 on 2022-09-15 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_rename_organization_location_member_org_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='applicable_shift',
        ),
        migrations.RemoveField(
            model_name='member',
            name='shift',
        ),
    ]
