# Generated by Django 4.0.2 on 2022-09-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_remove_member_applicable_shift_remove_member_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-created_at']},
        ),
    ]
