# Generated by Django 4.0.2 on 2022-09-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('member', '0024_alter_member_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='previous_roster',
        ),
        migrations.RemoveField(
            model_name='member',
            name='rosters',
        ),
        migrations.AddField(
            model_name='memberimage',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='member_images', to='organization.organization'),
            preserve_default=False,
        ),
    ]
