# Generated by Django 4.0.2 on 2022-10-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_remove_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='allowed_to_meet',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
