# Generated by Django 4.0.2 on 2022-10-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_alter_member_allowed_to_meet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='government_id_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pin_code',
        ),
    ]
