# Generated by Django 4.0.2 on 2022-10-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_department_department_head'),
        ('member', '0028_remove_profile_government_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='org_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organization.orglocation'),
        ),
    ]
