# Generated by Django 4.0.2 on 2022-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0029_alter_member_org_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberimage',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='member',
            name='is_front_desk',
            field=models.BooleanField(default=False),
        ),
    ]
