# Generated by Django 4.0.2 on 2022-07-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_rosters'),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='cluster', to='roster.Location'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='managers',
            field=models.ManyToManyField(related_name='clusters', to='member.Member'),
        ),
    ]
