# Generated by Django 4.0.2 on 2022-08-18 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_remove_member_shift'),
        ('roster', '0002_alter_cluster_locations_alter_cluster_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='shift',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
