# Generated by Django 4.0.2 on 2022-09-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_remove_attendance_roster'),
        ('roster', '0003_remove_roster_shift_delete_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roster',
        ),
    ]
