# Generated by Django 4.0.2 on 2022-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('roster', '0004_delete_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='cluster', to='organization.SystemLocation'),
        ),
    ]
