# Generated by Django 4.0.2 on 2023-02-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_cluster_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cluster',
        ),
    ]
