# Generated by Django 4.0.2 on 2022-08-18 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0017_remove_member_shift'),
        ('organization', '0004_alter_systemlocation_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('computation_time', models.TimeField()),
                ('present_working_hours', models.DurationField()),
                ('partial_working_hours', models.DurationField()),
                ('skip_days', models.JSONField(default=list)),
                ('enable_geo_fencing', models.BooleanField(default=True)),
                ('enable_check_in_time_restriction', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_created_by', to='member.member')),
                ('default_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.systemlocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_updated_by', to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='LocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('applicable_start_date', models.DateField()),
                ('applicable_end_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_settings_created_by', to='member.member')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift.shift')),
                ('system_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.systemlocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_settings_updated_by', to='member.member')),
            ],
        ),
    ]
