# Generated by Django 4.0.2 on 2022-08-19 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsettings',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_settings', to='shift.shift'),
        ),
    ]
