# Generated by Django 4.0.2 on 2022-08-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_alter_locationsettings_shift'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('name', 'description')},
        ),
    ]
