# Generated by Django 4.0.2 on 2022-09-10 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_rename_organization_location_member_org_location'),
        ('shift', '0004_shift_enable_face_recognition'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 9, 10)),
        ),
        migrations.CreateModel(
            name='ShiftScheduleLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedule_logs', to='member.member')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_schedule_logs', to='shift.shift')),
            ],
        ),
    ]
