# Generated by Django 4.0.2 on 2022-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_shift_end_date_shift_start_date_shiftschedulelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shiftschedulelogs',
            name='status',
            field=models.BooleanField(default='active'),
        ),
    ]
