# Generated by Django 4.0.2 on 2022-09-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_alter_shift_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelogs',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
