# Generated by Django 4.0.2 on 2022-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0007_alter_shiftschedulelogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftschedulelogs',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
