# Generated by Django 4.0.2 on 2022-09-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0008_alter_shift_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftschedulelogs',
            options={'ordering': ['-start_date']},
        ),
    ]
