# Generated by Django 4.0.2 on 2022-09-13 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_rename_organization_location_member_org_location'),
        ('shift', '0009_alter_shiftschedulelogs_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShiftScheduleLogs',
            new_name='ShiftScheduleLog',
        ),
    ]
