# Generated by Django 4.0.2 on 2022-09-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0010_rename_shiftschedulelogs_shiftschedulelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedulelog',
            name='is_employee_shift_mapping',
            field=models.BooleanField(default=False),
        ),
    ]
