# Generated by Django 4.0.2 on 2022-09-13 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0011_shiftschedulelog_is_employee_shift_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_date',
        ),
    ]
