# Generated by Django 4.0.2 on 2022-09-16 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_organization_default_shift'),
        ('shift', '0012_remove_shift_end_date_remove_shift_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedulelog',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftschedulelog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
