# Generated by Django 4.0.2 on 2022-09-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0014_rename_is_employee_shift_mapping_shiftschedulelog_is_ism'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftschedulelog',
            old_name='is_ism',
            new_name='is_esm',
        ),
    ]
