# Generated by Django 4.0.2 on 2022-09-16 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0016_shiftschedulelog_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
