# Generated by Django 4.0.2 on 2022-09-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0018_alter_shiftschedulelog_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftschedulelog',
            name='location_settings',
            field=models.ManyToManyField(to='shift.LocationSettings'),
        ),
    ]
