# Generated by Django 4.0.2 on 2022-09-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0019_shiftschedulelog_location_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsettings',
            name='shift',
        ),
    ]
