# Generated by Django 4.0.2 on 2022-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0020_remove_locationsettings_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='location_settings',
            field=models.ManyToManyField(related_name='shift_schedule_log', to='shift.LocationSettings'),
        ),
    ]
