# Generated by Django 4.0.2 on 2022-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0021_alter_shiftschedulelog_location_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsettings',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='enable_check_in_time_restriction',
        ),
        migrations.AddField(
            model_name='shift',
            name='location_start_time_restriction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_start_time_restriction',
            field=models.BooleanField(default=True),
        ),
    ]
