# Generated by Django 4.0.2 on 2022-09-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0023_locationsettings_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsettings',
            name='end_time',
            field=models.TimeField(),
        ),
    ]
