# Generated by Django 4.0.2 on 2022-09-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0024_alter_locationsettings_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='location_start_time_restriction',
            new_name='loc_settings_start_time_restriction',
        ),
    ]
