# Generated by Django 4.0.2 on 2022-09-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0027_attendancecomputationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecomputationhistory',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
