# Generated by Django 4.0.4 on 2022-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0028_alter_attendancecomputationhistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecomputationhistory',
            name='employee_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancecomputationhistory',
            name='status',
            field=models.CharField(choices=[('start', 'Start'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50),
        ),
    ]
