# Generated by Django 4.0.4 on 2022-09-27 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('shift', '0029_alter_attendancecomputationhistory_employee_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='default_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_default_locations', to='organization.systemlocation'),
        ),
    ]
