# Generated by Django 4.0.2 on 2022-09-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('shift', '0030_shift_organization_alter_shift_default_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('name', 'organization')},
        ),
    ]
