# Generated by Django 4.0.4 on 2022-09-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0030_shift_organization_alter_shift_default_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='partial_working_hours',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='present_working_hours',
        ),
    ]
