# Generated by Django 4.0.4 on 2022-09-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0031_remove_shift_partial_working_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='partial_working_hours',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='shift',
            name='present_working_hours',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='skip_days',
            field=models.JSONField(default=dict),
        ),
    ]
