# Generated by Django 4.0.4 on 2022-09-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0032_shift_partial_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecomputationhistory',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50),
        ),
    ]
