# Generated by Django 4.0.4 on 2022-09-28 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0033_alter_attendancecomputationhistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecomputationhistory',
            name='computation_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='attendancecomputationhistory',
            name='computation_started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
