# Generated by Django 4.0.4 on 2022-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0034_attendancecomputationhistory_computation_ended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancecomputationhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
