# Generated by Django 4.0.4 on 2022-09-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0035_alter_attendancecomputationhistory_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceComputationHistory',
        ),
    ]
