# Generated by Django 4.0.2 on 2022-09-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0031_alter_shift_unique_together'),
        ('shift', '0036_delete_attendancecomputationhistory'),
    ]

    operations = [
    ]
