# Generated by Django 4.0.4 on 2022-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0036_delete_attendancecomputationhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='skip_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
