# Generated by Django 4.0.2 on 2022-09-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0037_merge_20220928_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='location_settings',
            field=models.ManyToManyField(blank=True, related_name='shift_schedule_log', to='shift.LocationSettings'),
        ),
    ]
