# Generated by Django 4.0.2 on 2022-09-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('shift', '0038_alter_shiftschedulelog_location_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsettings',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationsettings',
            name='applicable_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
