# Generated by Django 4.0.4 on 2022-09-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0037_alter_shift_skip_days'),
        ('shift', '0039_locationsettings_organization_and_more'),
    ]

    operations = [
    ]
