# Generated by Django 4.0.4 on 2022-10-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_holiday_org_location'),
        ('shift', '0040_merge_20220930_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='holiday_org_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_holiday_org_locations', to='organization.orglocation'),
        ),
    ]
