# Generated by Django 4.0.2 on 2022-10-01 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('shift', '0040_merge_20220930_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='default_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_default_locations', to='organization.systemlocation'),
        ),
    ]
