# Generated by Django 4.0.2 on 2022-10-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0041_alter_shift_default_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='  ', max_length=50),
        ),
    ]
