# Generated by Django 4.0.4 on 2022-10-03 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_holiday_org_location'),
        ('shift', '0041_shift_holiday_org_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='holiday_org_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_holiday_org_locations', to='organization.orglocation'),
        ),
    ]
