# Generated by Django 4.0.2 on 2022-10-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0042_alter_shiftschedulelog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftschedulelog',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
