# Generated by Django 4.0.4 on 2022-10-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0042_alter_shift_holiday_org_location'),
        ('shift', '0043_alter_shiftschedulelog_status'),
    ]

    operations = [
    ]
