# Generated by Django 4.0.2 on 2022-10-18 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_organization_kiosk_management_settings'),
        ('shift', '0044_merge_20221003_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='default_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_default_locations', to='organization.systemlocation'),
        ),
    ]
