# Generated by Django 4.0.2 on 2022-11-02 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0046_alter_locationsettings_options_alter_shift_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='holiday_org_location',
        ),
    ]
