# Generated by Django 4.0.2 on 2023-03-02 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_alter_orglocation_org_location_head'),
        ('shift', '0047_remove_shift_holiday_org_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='default_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_default_locations', to='organization.systemlocation'),
        ),
    ]
