# Generated by Django 4.0.2 on 2022-08-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp',
            field=models.CharField(default=1111, max_length=4),
            preserve_default=False,
        ),
    ]
