# Generated by Django 4.0.2 on 2022-08-04 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import visitor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_alter_systemlocation_radius_and_more'),
        ('kiosk', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=visitor.models.rename_visitor_image)),
                ('inactive_days', models.IntegerField(default=0)),
                ('visitor_company', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_kiosks', models.ManyToManyField(blank=True, related_name='visitor', to='kiosk.Kiosk')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='organization.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='organization.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
