# Generated by Django 4.0.2 on 2022-08-05 04:54

from django.db import migrations, models
import django.db.models.deletion
import uuid
import visitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image', models.ImageField(upload_to=visitor.models.rename_visitor_face_rec_image)),
                ('encoding', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
    ]
