# Generated by Django 4.0.2 on 2022-08-05 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_visitorimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorimage',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_images', to='visitor.visitor'),
        ),
    ]
