# Generated by Django 4.0.2 on 2022-08-05 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid
import visitor.models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_initial'),
        ('visitor', '0003_alter_visitorimage_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('photo', models.ImageField(upload_to=visitor.models.rename_visitor_scan_image)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_computed', models.BooleanField(default=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.kiosk')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor.visitor')),
            ],
        ),
    ]
