# Generated by Django 4.0.2 on 2022-08-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0005_visitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitation',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
