# Generated by Django 4.0.2 on 2022-08-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0006_alter_visitation_description'),
    ]

    operations = [
      
    ]
