# Generated by Django 4.0.2 on 2022-08-06 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_systemlocation_radius_and_more'),
        ('visitor', '0008_remove_visitation_status_visitation_host_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitation',
            name='org_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitation', to='organization.organizationlocation'),
        ),
    ]
