# Generated by Django 4.0.2 on 2022-08-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0010_alter_visitation_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitation',
            options={'ordering': ['-visitation_date']},
        ),
        migrations.AlterField(
            model_name='visitation',
            name='host_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='visitation_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='visitation_status',
            field=models.CharField(choices=[('created', 'Created'), ('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='visitation',
            name='visitor_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50),
        ),
    ]
