# Generated by Django 4.0.2 on 2022-08-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0012_visitorscan_visitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorscan',
            name='visitation',
        ),
    ]
