# Generated by Django 4.0.2 on 2022-08-09 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0013_remove_visitorscan_visitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorscan',
            name='visitation',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='visitor.visitation'),
            preserve_default=False,
        ),
    ]
