# Generated by Django 4.0.2 on 2022-08-09 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0004_alter_systemlocation_radius_and_more'),
        ('visitor', '0014_visitorscan_visitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('organization', 'user')},
        ),
    ]
