# Generated by Django 4.0.2 on 2022-08-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_alter_visitor_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorscan',
            name='is_computed',
        ),
    ]
