# Generated by Django 4.0.2 on 2022-08-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0017_alter_visitorscan_date_alter_visitorscan_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorscan',
            options={'ordering': ['date']},
        ),
    ]
