# Generated by Django 4.0.2 on 2022-08-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0020_delete_visitorimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitation',
            options={'ordering': ['-created_at']},
        ),
    ]
