# Generated by Django 4.0.2 on 2022-08-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0021_alter_visitation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='authorized_kiosks',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='photo',
        ),
    ]
