# Generated by Django 4.0.2 on 2022-09-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0023_alter_visitation_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitation',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
