# Generated by Django 4.0.2 on 2022-10-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0025_visitation_organization_visitorscan_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='visitorscan',
            options={'ordering': ['-date']},
        ),
    ]
