# Generated by Django 4.0.2 on 2022-07-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kiosk',
        ),
    ]
