# Generated by Django 4.0.2 on 2022-07-27 11:24

from django.db import migrations, models
import django.db.models.deletion
import kiosk.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('kiosk', '0002_delete_kiosk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiosk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kiosk_name', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('settings', models.JSONField(blank=True, default=kiosk.models.default_kiosk_settings, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosks', to='organization.organization')),
            ],
        ),
    ]
