# Generated by Django 4.0.2 on 2022-08-09 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiosk',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='kiosk',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
