# Generated by Django 4.0.2 on 2022-10-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_kiosk_org_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='access_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kiosk',
            name='dit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='dit_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
