# Generated by Django 4.0.4 on 2022-10-12 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_organization_kiosk_management_settings'),
        ('kiosk', '0006_kiosk_access_code_kiosk_dit_kiosk_dit_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosk',
            name='org_location',
        ),
        migrations.AddField(
            model_name='kiosk',
            name='org_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.orglocation'),
            preserve_default=False,
        ),
    ]
