# Generated by Django 4.0.2 on 2022-10-12 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_organization_kiosk_management_settings'),
        ('kiosk', '0007_remove_kiosk_org_location_kiosk_org_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiosk',
            name='org_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.orglocation'),
        ),
    ]
