# Generated by Django 4.0.2 on 2023-03-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0010_alter_kiosk_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='installed_latitude',
            field=models.DecimalField(decimal_places=7, default=22.9868, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kiosk',
            name='installed_longitude',
            field=models.DecimalField(decimal_places=7, default=87.855, max_digits=9),
            preserve_default=False,
        ),
    ]
