# Generated by Django 4.0.4 on 2022-06-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('organization', '0001_initial'),
        ('roster', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentbydefault',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='present_by_default', to='member.member'),
        ),
        migrations.AddField(
            model_name='presentbydefault',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_by_default', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='memberscan',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='member.member'),
        ),
        migrations.AddField(
            model_name='memberscan',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='roster.roster'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='member.member'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='roster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='roster.roster'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='scans',
            field=models.ManyToManyField(blank=True, related_name='attendance', to='attendance.memberscan'),
        ),
    ]
