# Generated by Django 4.0.2 on 2022-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_rosters'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='scans',
            field=models.ManyToManyField(blank=True, related_name='attendance', to='attendance.MemberScan'),
        ),
        migrations.AlterField(
            model_name='presentbydefault',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='present_by_default', to='member.Member'),
        ),
    ]
