# Generated by Django 4.0.2 on 2022-09-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_shift_enable_face_recognition'),
        ('attendance', '0003_alter_attendance_scans_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscan',
            name='roster',
        ),
        migrations.AddField(
            model_name='memberscan',
            name='location_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='shift.locationsettings'),
        ),
    ]
