# Generated by Django 4.0.4 on 2022-09-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_memberscan_roster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('computed', 'Computed'), ('expired', 'Expired')], default='pending', max_length=200),
        ),
    ]
