# Generated by Django 4.0.4 on 2022-09-27 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_memberscan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscan',
            name='is_validated',
        ),
    ]
