# Generated by Django 4.0.2 on 2022-09-27 09:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_alter_kiosk_end_time_alter_kiosk_start_time'),
        ('attendance', '0006_remove_memberscan_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberscan',
            name='datetime',
        ),
        migrations.AddField(
            model_name='memberscan',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 27)),
        ),
        migrations.AddField(
            model_name='memberscan',
            name='kiosk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kiosk.kiosk'),
        ),
        migrations.AddField(
            model_name='memberscan',
            name='time',
            field=models.TimeField(default=datetime.time(9, 19, 27, 735653)),
        ),
    ]
