# Generated by Django 4.0.4 on 2022-09-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_remove_memberscan_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='overtime',
        ),
    ]
