# Generated by Django 4.0.4 on 2022-09-28 09:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0036_delete_attendancecomputationhistory'),
        ('attendance', '0008_attendance_duration_attendance_early_check_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceComputationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('employee_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=50)),
                ('computation_started_at', models.DateTimeField()),
                ('computation_ended_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_history', to='shift.shift')),
            ],
        ),
    ]
