# Generated by Django 4.0.2 on 2022-09-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('attendance', '0008_alter_memberscan_date_alter_memberscan_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberscan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='memberscan',
            name='location_settings',
        ),
        migrations.AddField(
            model_name='memberscan',
            name='system_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='organization.systemlocation'),
        ),
    ]
