# Generated by Django 4.0.2 on 2022-09-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_alter_memberscan_options_and_more'),
        ('attendance', '0009_attendancecomputationhistory'),
    ]

    operations = [
    ]
