# Generated by Django 4.0.4 on 2022-09-30 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('attendance', '0009_attendancecomputationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecomputationhistory',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_computation_histories', to='organization.organization'),
            preserve_default=False,
        ),
    ]
