# Generated by Django 4.0.2 on 2022-09-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
        ('attendance', '0010_merge_20220928_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscan',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.organization'),
            preserve_default=False,
        ),
    ]
