# Generated by Django 4.0.4 on 2022-09-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancecomputationhistory_organization'),
        ('attendance', '0011_memberscan_organization'),
    ]

    operations = [
    ]
