# Generated by Django 4.0.2 on 2022-09-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_merge_20220930_1929'),
        ('attendance', '0012_remove_attendance_roster'),
    ]

    operations = [
    ]
