# Generated by Django 4.0.2 on 2022-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_remove_memberscan_date_remove_memberscan_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscan',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
