# Generated by Django 4.0.2 on 2022-10-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_attendance_visited_system_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberscan',
            name='scan_type',
            field=models.CharField(choices=[('check_in', 'Check IN'), ('check_out', 'Check Out')], default='check_in', max_length=200),
        ),
    ]
