# Generated by Django 4.0.2 on 2022-10-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_memberscan_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscan',
            name='scan_type',
            field=models.CharField(choices=[('check_in', 'Check IN'), ('check_out', 'Check Out')], max_length=200),
        ),
    ]
