# Generated by Django 4.0.2 on 2022-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_alter_memberscan_scan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberscan',
            name='scan_type',
            field=models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=200),
        ),
    ]
