# Generated by Django 4.0.2 on 2023-01-30 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_alter_attendancecomputationhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecomputationhistory',
            name='attendance_date',
            field=models.DateField(default=datetime.date(2023, 1, 10)),
        ),
    ]
