# Generated by Django 4.0.2 on 2023-01-30 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_remove_attendancecomputationhistory_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecomputationhistory',
            name='attendance_date',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
