# Generated by Django 4.0.2 on 2023-02-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_alter_attendancecomputationhistory_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancecomputationhistory',
            name='attendance_date',
        ),
    ]
