# Generated by Django 4.0.2 on 2023-03-29 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0048_alter_shift_default_location'),
        ('attendance', '0029_remove_attendancecomputationhistory_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shift.shift'),
        ),
    ]
