# Generated by Django 4.0.2 on 2023-03-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_attendance_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='ot_status',
            field=models.CharField(blank=True, choices=[('ot_requested', 'OT requested'), ('ot_approved', 'OT Approved'), ('ot_rejected', 'OT rejected')], max_length=50, null=True),
        ),
    ]
