# Generated by Django 4.0.2 on 2023-10-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_attendance_ot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='late_check_out',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
