# Generated by Django 4.0.2 on 2023-10-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_alter_memberimage_options_member_is_front_desk'),
        ('attendance', '0033_attendance_ot_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='ot_approved_by',
        ),
        migrations.AddField(
            model_name='attendance',
            name='ot_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='member.member'),
        ),
    ]
