# Generated by Django 4.0.2 on 2023-11-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_remove_attendance_ot_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='ot_status',
            field=models.CharField(blank=True, choices=[('ot_available', 'OT Available'), ('ot_requested', 'OT requested'), ('ot_approved', 'OT Approved'), ('ot_rejected', 'OT rejected')], max_length=50, null=True),
        ),
    ]
