# Generated by Django 4.0.2 on 2024-04-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_attendance_remarks_alter_attendance_ot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecomputationhistory',
            name='attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
