# Generated by Django 4.0.4 on 2022-06-16 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave', '0001_initial'),
        ('organization', '0001_initial'),
        ('roster', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizationworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularization_workflow_created_by', to='member.member'),
        ),
        migrations.AddField(
            model_name='regularizationworkflow',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_workflows', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='regularizationworkflow',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularization_workflow_updated_by', to='member.member'),
        ),
        migrations.AddField(
            model_name='regularizationrequestactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regularization_request_activities_created_by', to='member.member'),
        ),
        migrations.AddField(
            model_name='regularizationrequestactivity',
            name='regularization_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_request_activities', to='leave.regularizationrequest'),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularization_requests', to='member.member'),
        ),
        migrations.AddField(
            model_name='regularizationrequest',
            name='regularization_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='leave.regularizationworkflow'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='leaverequestactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request_activities_created_by', to='member.member'),
        ),
        migrations.AddField(
            model_name='leaverequestactivity',
            name='leave_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_activities', to='leave.leaverequest'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approval_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='leave.approvalworkflow'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='member.member'),
        ),
        migrations.AddField(
            model_name='leavebalanceactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_balance_activities', to='member.member'),
        ),
        migrations.AddField(
            model_name='leavebalanceactivity',
            name='leave_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_activities', to='leave.leavebalance'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='member.member'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_workflow_created_by', to='member.member'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_workflow_updated_by', to='member.member'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='organization.department'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='designations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='organization.designation'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='exclude_departments',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='organization.department'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='exclude_designations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='organization.designation'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='exclude_locations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='roster.location'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='exclude_members',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='member.member'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='exclude_roles',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='organization.role'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='leave_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicability', to='leave.leavetype'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='roster.location'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='member.member'),
        ),
        migrations.AddField(
            model_name='applicability',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='organization.role'),
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('member', 'leave_type')},
        ),
    ]
