# Generated by Django 4.0.2 on 2022-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('member', '0004_alter_member_rosters'),
        ('roster', '0002_alter_cluster_locations_alter_cluster_managers'),
        ('leave', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicability',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='organization.Department'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='designations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='organization.Designation'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='exclude_departments',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='organization.Department'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='exclude_designations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='organization.Designation'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='exclude_locations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='roster.Location'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='exclude_members',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='exclude_roles',
            field=models.ManyToManyField(blank=True, related_name='applicabilities_exclusion', to='organization.Role'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='roster.Location'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='applicability',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='applicabilities', to='organization.Role'),
        ),
    ]
