# Generated by Django 4.0.2 on 2022-07-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationlocation',
            name='approval_workflow',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='regularization_workflow',
        ),
        migrations.RemoveField(
            model_name='organizationlocation',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='organizationlocation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
