# Generated by Django 4.0.2 on 2022-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_systemlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlocation',
            name='radius',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterUniqueTogether(
            name='systemlocation',
            unique_together={('organization', 'name')},
        ),
    ]
