# Generated by Django 4.0.2 on 2022-08-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_department_shift_designation_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlocation',
            name='enable_visitation',
            field=models.BooleanField(default=True),
        ),
    ]
