# Generated by Django 4.0.2 on 2022-09-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0023_alter_visitation_end_time'),
        ('member', '0022_rename_organization_location_member_org_location'),
        ('shift', '0004_shift_enable_face_recognition'),
        ('organization', '0007_organization_default_shift_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationLocation',
            new_name='OrgLocation',
        ),
    ]
