# Generated by Django 4.0.2 on 2022-09-08 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_shift_enable_face_recognition'),
        ('organization', '0008_rename_organizationlocation_orglocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orglocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_locations', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='orglocation',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org_locations', to='shift.shift'),
        ),
    ]
