# Generated by Django 4.0.2 on 2022-09-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0009_alter_shiftschedulelogs_options'),
        ('organization', '0010_alter_organization_default_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_shift',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='shift.shift'),
            preserve_default=False,
        ),
    ]
