# Generated by Django 4.0.2 on 2022-09-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0015_rename_is_ism_shiftschedulelog_is_esm'),
        ('organization', '0011_alter_organization_default_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shift.shift'),
        ),
    ]
