# Generated by Django 4.0.4 on 2022-09-27 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0029_alter_attendancecomputationhistory_employee_count_and_more'),
        ('organization', '0012_alter_organization_default_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='shift.shift'),
        ),
    ]
