# Generated by Django 4.0.4 on 2022-10-01 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='org_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays', to='organization.orglocation'),
        ),
    ]
