# Generated by Django 4.0.2 on 2022-10-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_default_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_org_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organization.orglocation'),
        ),
    ]
