# Generated by Django 4.0.4 on 2022-10-03 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_holiday_org_location'),
        ('organization', '0014_organization_default_org_location'),
    ]

    operations = [
    ]
