# Generated by Django 4.0.4 on 2022-10-03 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_merge_20221003_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='org_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holidays', to='organization.orglocation'),
        ),
    ]
