# Generated by Django 4.0.2 on 2022-10-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_remove_profile_city'),
        ('organization', '0017_rename_address_organization_location_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
