# Generated by Django 4.0.2 on 2022-10-12 10:51

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_alter_state_unique_together_remove_state_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kiosk_management_settings',
            field=models.JSONField(blank=True, default=organization.models.default_kiosk_management_settings),
        ),
    ]
