# Generated by Django 4.0.2 on 2022-10-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_organization_kiosk_management_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlocation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
