# Generated by Django 4.0.2 on 2022-10-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_department_department_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='orglocation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='systemlocation',
            options={'ordering': ['-updated_at']},
        ),
    ]
