# Generated by Django 4.0.2 on 2022-10-31 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_alter_department_options_alter_designation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='is_recurring',
        ),
    ]
