# Generated by Django 4.0.2 on 2022-11-01 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_remove_holiday_is_recurring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='org_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='organization.orglocation'),
        ),
    ]
