# Generated by Django 4.0.2 on 2023-01-06 08:16

from django.db import migrations, models
import organization.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_alter_holiday_org_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='limit',
            field=models.JSONField(blank=True, default=organization.models.default_limit_settings, null=True),
        ),
    ]
