# Generated by Django 4.0.2 on 2023-02-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0025_organization_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='enable_field_report',
            field=models.BooleanField(default=False),
        ),
    ]
