# Generated by Django 4.0.2 on 2023-02-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_department_enable_field_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='enable_field_report',
        ),
    ]
