# Generated by Django 4.0.2 on 2023-02-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_alter_memberimage_options_member_is_front_desk'),
        ('organization', '0027_remove_department_enable_field_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_head',
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ManyToManyField(blank=True, related_name='department_head', to='member.Member'),
        ),
    ]
