# Generated by Django 4.0.2 on 2023-02-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_alter_memberimage_options_member_is_front_desk'),
        ('organization', '0028_remove_department_department_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orglocation',
            name='org_location_head',
            field=models.ManyToManyField(blank=True, to='member.Member'),
        ),
    ]
