# Generated by Django 4.0.2 on 2023-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_alter_memberimage_options_member_is_front_desk'),
        ('organization', '0029_orglocation_org_location_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orglocation',
            name='org_location_head',
            field=models.ManyToManyField(blank=True, related_name='org_location_head', to='member.Member'),
        ),
    ]
