# Generated by Django 4.0.2 on 2023-07-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0030_alter_orglocation_org_location_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_attendance_computed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
