# Generated by Django 4.0.2 on 2024-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0031_organization_last_attendance_computed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=200),
        ),
    ]
