# Generated by Django 4.0.2 on 2024-08-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0032_alter_organization_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
    ]
